config/routes.rb
Rails.application.routes.draw do

  get 'coupons/show'

  resources :shops , only: %i[index show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'dashboards#home'
  resources :cashbacks, only: %i[new create index]
  resource :dashboard, only: %i[show home]
  devise_for :users
  resource :coupons, only: %i[show new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cashback.rb
class Cashback < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  validates :amount, presence: true
  validates :ticket, presence: true
  # validation de montant sitrictement positif
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :user
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many_attached :photos
  
  has_many :cashbacks
  validates :name, presence: true
  validates :address, presence: true
  validates :active, default: false # actif après validation du format de ticket
  # validates :latitude, presence: true
  # validates :longitude, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_attachment :avatar

  has_many :cashbacks
  has_many :coupons
  # has_many :shops through: :cashback

  def total_cashback
    cashbacks.pluck(:amount).sum
  end

  def total_coupon
    coupons.pluck(:price).sum
  end

  def current_cashback
    total_cashback - total_coupon
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :init_scan


  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def init_scan
    @new_cashback = Cashback.new
  end
end

app/controllers/cashbacks_controller.rb
class CashbacksController < ApplicationController
  def new
    @new_cashback = Cashback.new
  end

  def index
    @cashbacks=Cashback.all
  end

  def create
    @new_cashback = Cashback.new(user: current_user)

    @file = params[:cashback][:ticket]
    result = TicketReaderService.new(@file).call

    if result[:status] == :success
      @new_cashback.shop = Shop.find_by(siret: result[:siret]) || Shop.find_by(raw_name: result[:name], address: result[:address])
      @new_cashback.amount = result[:cashback_amount]
      @new_cashback.ticket_amount = result[:total_amount]

      redirect_to(root_path, notice: "#{result[:name]} n'est pas un magasin affilié !") and return unless @new_cashback.save

      redirect_to dashboard_path
    else
      redirect_to(root_path, notice: result[:error_message])
    end
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  def show
    @coupons = current_user.coupons.order(created_at: :desc)
  end

  def new
    @new_coupon = Coupon.new
    @sum_cashback = current_user.current_cashback
  end

  def create
    @new_coupon = Coupon.new(coupon_params)
    if current_user.current_cashback < @new_coupon.price
      flash.alert = "Vous n'avez pas assez de cashback!"
      render "coupons/new" 
      return
    end

    @new_coupon.user = current_user

    code = Digest::MD5.hexdigest("#{current_user.id}x#{current_user.coupons.count + 1}")
    @new_coupon.code = "NINCOUPON-#{code}"[0..15].upcase
    @new_coupon.save
    redirect_to coupons_path
  end

  private
  def coupon_params
    params.require(:coupon).permit(:price)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home
  def show
    @sum_cashback = current_user.current_cashback

    @cashback = Cashback
      .where(user: current_user)
      .last
  end

  def home
    @shops= [Shop.first , Shop.second , Shop.third]
    
    # @shops = Cashback.shop.all .sort_by!{|item| item[:name]} .sort_by{|shopid| shopid [:shop_id]}
    # @shops = Shop.all
    # @top = Hash.new
    # @top = @shops.each do |shop|
      
    #  [shop.id] = shop.cashbacks.pluck(:amount).sum
    #  binding.pry
    # end
    # binding.pry
    
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops=Shop.all
  end

  def show
    @shop=Shop.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/cashbacks/create.html.erb
<h1>Cashbacks#create</h1>
<p>Find me in app/views/cashbacks/create.html.erb</p>

app/views/cashbacks/index.html.erb
<%@disable_logo=true %>

<div class="dashboard_resume">
  <h2>Mes Cashbacks</h2>
  <h3>Historique de vos cashbacks</h3>

  <div class="cashback-container">
      <% @cashbacks.each do |cashback| %>
        <div class="cashback-each">
          <%= cashback.created_at.strftime("%d/%m/%Y") %>
          <%= link_to cashback.shop.name, shops_path(cashback.shop) %>
          <%= cashback.amount %> €
        </div>
      <% end %>
  </div>

  <a class="btn btn-fix" href= "/coupons/new">Générer un coupon de réduction</a>

  <div>
    <a class="btn btn-gradient" href= "/shops">Revenir à la liste des partenaires affiliés</a>
  </div>
</div>

app/views/cashbacks/new.html.erb
  <h2 class="erreur">Une erreur est survenu</h2>
  <div class = "scan-ticket">
    <%= simple_form_for @new_cashback, html: {data: {controller: "ticket-submit"}} do |f|%>
      <%= f.label :ticket, "Réessayer", class: "btn btn-gradient" %>
      <%= f.file_field :ticket, accept: "image/*", capture: "environment", data: {action: "change->ticket-submit#submit"}, class: "d-none" %>
    <% end %>
  </div>
 

app/views/coupons/new.html.erb
<h2>Utiliser mon cashback</h2>
<%#  solde disponible %>
<div class="gencash">
  <div class="soldecashback">
    <h4> Solde actuel:</h4><h4 id="euro"> <%= @sum_cashback %> € </h4> 
  </div>
  
  <div class="form_coupon">
    <%=simple_form_for @new_coupon do |form|%>
      <%= form.input :price, label: "Entrez le montant", class: "label"%>
      <%= form.submit "Générer", class: "btn btn-solid myrendre" %>
    <% end%>
  </div>
</div>

app/views/coupons/show.html.erb
<div class="coupon-index">
<h2>Comment profiter de mon cashback? </h2>
  <div class="explications">
    <p>Le cashback cumulé grâce à l'application Nice is Nice permet de générer des coupons de réductions.</p> 
    <p>Ces coupons sont utilisables pour l'achat de billets d'entrées à des évènements, expositions ou manifestations organisés par la ville de Nice.</p> 
    <a class="btn btn-solid myrendre" href= "https://www.nicetourisme.com/agenda">Je découvre les évènements de la ville </a>
  </div>
  
  <div class="generate_coupon">
    <h1>Mes coupons de réduction générés</h1>
  </div>
  <% if @coupons.present? %>
    <% @coupons.each do |coupon|%>
      <div class="code">
        <h4>Code : <%= coupon.code%></h4>
        <div class="price"><h5>
          <%= coupon.price%>€</h5>
        </div>
        <div class="date_time">
          <h6>Le <%= coupon.created_at.strftime('%d/%m/%Y à %H:%M')%></h6>
        </div>  
      </div>
    <% end %>
  <%else%>  
    <div class="code"><h4>Vous n'avez pas de coupons</h4></div>
  <% end %>
  </div>
</div>

app/views/dashboards/home.html.erb
<%# Now let's assume you have an Offer model and you want dynamic titles and descriptions for any products#show page. %>
<%# <% content_for :meta_title, "#{@offer.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<%# <% content_for :meta_description, @offer.description %>
<%# <% content_for :meta_image, cl_image_path(@offer.photo.path) %>
<div class="banner">
  <div class="container">
    <h1>Nice is Nice! </h1>
    <h2>Le cashback citoyen <strong>qui te fait sortir</strong></h2>
  </div>

    <div class="container">
      <h3>Comment l'application fonctionne-t-elle?</h3> 
      <p>1. Scan ton ticket de caisse après achat au sein des commerces locaux niçois. Obtiens 5% de cashback à chaque fois.</p> 
      <p>2. Convertis ton cashback en coupon de réduction</p>
      <p>3. Utilise ton coupon de réduction lors de l'achat d'un billet d'entrée aux évènements culturels niçois </p>
    </div>

  <div class = "scanticket">
    <%= simple_form_for @new_cashback, html: {data: {controller: "ticket-submit"}} do |f|%>
      <%= f.label :ticket, "Scanner un ticket", class: "btn btn-gradient" %>
      <%= f.file_field :ticket, accept: "image/*", capture: "environment", data: {action: "change->ticket-submit#submit"}, class: "d-none" %>
    <% end %>
  </div>
</div>

<div class="toptrois">
  <h2>Top 3 commerces</h2>
</div>

    <% @shops.each do |shop| %>
    <% @shop = shop%>
      <div class="container">
        <div class="card-product">
          <div class="card-product-top">
            <div class="card-product-top-image">
              <%# cl_image_tag(@shop.photos.second.key, :size => '150x150', :crop => :fill) %>           
              <i class="fas fa-heart position-icon"></i>
            </div>
            <div class="card-product-info" style="text-align:center;">
              <div>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="far fa-star"></i>
              </div>
              
              <p><strong><%= link_to shop.name, shop_path(shop)%></strong></p>
              <p><%=shop.address%></p>
              <span data-controller="visite-map" data-action="click->visite-map#openNativeMap" data-visite-map-longitude-value="<%= shop.longitude %>" data-visite-map-latitude-value="<%= shop.latitude %>" class="btn-solid myrendre"> Y aller </span>
            </div>
          </div>

          <div class="card-product-bottom">
            <%= cl_image_tag(@shop.photos.first.key, :size => '290x100',:crop => :fill) %>        
          </div>
        </div>
      </div> 
    <% end %>
  

  <div class="shopsaround">
    <%= link_to "Découvrir les commerces du réseau", shops_path, class: "btn btn-solid myrendre"%>
  </div>

app/views/dashboards/show.html.erb
<div class="background txt-white-center">

  <div class="container_informations">
    <div class="cashback_immediat">
      <h1>Dernier Cashback immediat</h1>
        <div class="now_amount">
          <div id="amount" class="text-center"><%= @cashback.amount.presence || 0 %> €</div>
          <div class="text-center mr-2 mb-4">sur un montant de <%= @cashback.ticket_amount %> €</div>
          <div class="cashback_details">
            <i class="fas fa-store"></i><%= link_to(@cashback.shop.name, shop_path(@cashback.shop)) %>
            <i class="fas fa-map-marker"></i><span><%= @cashback.shop.address %></span>
            <i class="fas fa-clock"></i><span><%= l(@cashback.created_at, format: "Ajouté le %d %b %Y à %Hh%M", locale: :fr) %></span>
          </div>
      </div>
    </div>
  </div>

  <div class="cashback_total">
    <h1>Cashback total</h1>
    <div class="total_amount">
      <p id="total"><%= @sum_cashback %> €</p>
    </div>  
  </div>


  <div>
    <a class="btn btn-fix" href= "/coupons/new" >Utiliser mon cashback</a>
  </div>

  <div>
    <a class="btn btn-solid myrendre" href= "/cashbacks" >Mes cashbacks</a>
  </div>

  <div>
    <a class="btn btn-solid myrendre" href= "/coupons" >Mes coupons de réductions</a>
  </div>
</div>

app/views/events/index.html.erb
<h2>Les évènements sur Nice <strong>à proximité</strong></h2>
<p>Découvrez l'agenda des évènements niçois</p>



<div class="card-trip">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <div class="card-trip-infos">
    <div>
      <h2>Title here</h2>
      <p>Short description here!</p>
    </div>
    <h2 class="card-trip-pricing">£99.99</h2>
    <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= favicon_link_tag %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
  </head>

  <body>
    <main>
      <%= render 'shared/flashes' %>
      <%= render 'shared/header'%>
      <%= yield %>
    </main>

    <navbar>
      <%= render 'shared/navbar' unless  @disable_navbar %>
      <div class="spinner-bg d-none">
        <div class="spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
        <div class="text-chargement">Ticket en cours d'analyse...</div>
      </div>
    </navbar>

  </body>
</html>

app/views/shared/_flashes.html.erb
<%#  Alert and notice %>
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<%= render 'shared/searchbar' unless  @disable_searchbar %>

<div class="logo">
    <%=image_tag("Nice_is_nice_logo_ok.png") unless  @disable_logo%>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar-links">
    <div class="nav-container">
    <%# Home %>
      <div class="nav-item">
        <%= link_to root_path, class: "nav-link" do%>
        <%= icon("fas", "home") %>
        <%end%>
      </div>

    <%# Event list %>
    <div class="nav-item">
      <%= link_to "https://www.nicetourisme.com/agenda", class: "nav-link" do%>
      <%= icon("fas", "calendar-alt") %>
      <%end%>
    </div>
  </div>

  <%= simple_form_for @new_cashback, html: {data: {controller: "ticket-submit"}} do |f|%>
    <%= f.label :ticket do %>
      <%# Scan a ticket %>
      <div class="nav-item">
          <%# <%= link_to new_cashback_path, class: "nav-link" do%>
          <%= icon("fas", "plus-circle") %>
          <%# <%end%>
      </div>
    <% end %>
    <%= f.file_field :ticket, accept: "image/*", capture: "environment", data: {action: "change->ticket-submit#submit"}, class: "d-none" %>
  <% end %>

  <div class="nav-container">
    <%# Shop list %>
    <div class="nav-item">
      <%= link_to shops_path, class: "nav-link" do%>
      <%= icon("fas", "store") %>
      <%end%>
    </div>

    <%# Dashboard %>
    <div class="nav-item">
      <%= link_to dashboard_path, class: "nav-link" do%>
        <%= icon("fas", "euro-sign") %>
      <%end%>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="searchbar">
      <input type="text" class="searchTerm" placeholder="Rechercher">
      <button type="submit" class="searchButton">
        <i class="fa fa-search"></i>
     </button>
   </div>
</div>

app/views/shops/index.html.erb
<h3>Les commerces du réseau <strong> Nice is Nice!</strong></h3>
<p><strong>Découvrez où vous pouvez récolter du cashback</strong></p>

<% @shops.each do |shop| %>
  <% @shop = shop%>
  <div class="container">
    <div class="card-product">
      <div class="card-product-top">
        <div class="card-product-top-image">
          <%# cl_image_tag(@shop.photos.second.key, :size => '150x150', :crop => :fill) %>           
          <i class="fas fa-heart position-icon"></i>
        </div>
        <div class="card-product-info" style="text-align:center;">
          <div>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
          </div>
          
          <p><strong><%= link_to shop.name, shop_path(shop)%></strong></p>
          <p><%=shop.address%></p>
          <span data-controller="visite-map" data-action="click->visite-map#openNativeMap" data-visite-map-longitude-value="<%= shop.longitude %>" data-visite-map-latitude-value="<%= shop.latitude %>" class="btn-solid myrendre"> Y aller </span>
        </div>
      </div>

      <div class="card-product-bottom">
        <%= cl_image_tag(@shop.photos.first.key, :size => '290x100',:crop => :fill) %>        
      </div>
    </div>
  </div> 
<% end %>

app/views/shops/new.html.erb
<h1>Shops#new</h1>
<p>Find me in app/views/shops/new.html.erb</p>

app/views/shops/show.html.erb
<h1>Toutes les informations de votre commerçant niçois préféré ici</h1>

<div class="container" style="text-align:center;">
  <h2><%= @shop.name %></h2>
  <p><%= @shop.address %></p>
  <span data-controller="visite-map" data-action="click->visite-map#openNativeMap" data-visite-map-longitude-value="<%= @shop.longitude %>" data-visite-map-latitude-value="<%= @shop.latitude %>" class="btn-solid myrendre"> Y aller </span>
</div>